PATH_DRIFT: ../data/Dumont-etal_2019/datasets2\ISMER_20140704_spot241_drift.tab
PATH_WATER: C:/Users/manon/Desktop/Thesis/data/HYCOM/data_ISMER_20140704_spot241_drift.nc4
PATH_WAVES: C:/Users/manon/Desktop/Thesis/data/ERA5_Wind/WaveData.nc
PATH_WIND: C:/Users/manon/Desktop/Thesis/data/ERA5_Wind/WindData.nc
max_lat: 51
max_lon: -57
min_lat: 48
min_lon: -60
